---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age1a5986megwwjggj9m2j4fftf3pqj6282vdmv5p4azhtk2gmxufsdqumhsdm"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age1a5986megwwjggj9m2j4fftf3pqj6282vdmv5p4azhtk2gmxufsdqumhsdm"
stores:
  yaml:
    indent: 2
